[project]
name = "basecamp3-fullstack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yagna247ai-star", email = "yagna247.ai@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
basecamp3-fullstack = "basecamp3_fullstack:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
